[package]
name = "irc"
version = "0.1.0"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]

[dev-dependencies]
env_logger = "^0.3.1"

[dependencies]
regex = "^0.1.41"
lazy_static = "^0.1.14"
log = "^0.3.2"
